name: Ping Streamlit App

on:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours
  workflow_dispatch:        # allow manual run from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit app
        run: |
          curl -L --silent https://fcragendaldh.streamlit.app/ > /dev/null
